
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


-- CREATION DE LA BASE DE DONNEES
CREATE DATABASE senegal_auto CHARACTER SET utf8 COLLATE utf8_general_ci;
USE senegal_auto;

--
-- Base de données :  `senegal_auto`
--


--
-- Structure de la table `administrateur`
--

DROP TABLE IF EXISTS `administrateur`;
CREATE TABLE IF NOT EXISTS `administrateur` (
  `nom_complet` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(65) NOT NULL,
  PRIMARY KEY (`password`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `administrateur`
--

INSERT INTO `administrateur` (`nom_complet`, `email`, `password`) VALUES
('Djiby Sarr', 'sarrdjiby20@gmail.com', 'senegal-auto2020');

-- --------------------------------------------------------

--
-- Structure de la table `image`
--

DROP TABLE IF EXISTS `image`;
CREATE TABLE IF NOT EXISTS `image` (
  `nom_image` varchar(50) NOT NULL,
  `chemin_image` varchar(100) NOT NULL,
  `nombre_photos` tinyint(2) NOT NULL,
  `numero_voiture` int(5) NOT NULL,
  PRIMARY KEY (`nom_image`),
  KEY `numero_voiture` (`numero_voiture`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `image`
--

INSERT INTO `image` (`nom_image`, `chemin_image`, `nombre_photos`, `numero_voiture`) VALUES
('02_04_2021_0224_1', '/our_vehicule/02_04_2021_0224_1.jpg', 10, 224),
('02_04_2021_1016_1', '/our_vehicule/02_04_2021_1016_1.jpg', 8, 1016),
('02_04_2021_1257_1', '/our_vehicule/02_04_2021_1257_1.jpg', 7, 1257),
('02_04_2021_2007_1', '/our_vehicule/02_04_2021_2007_1.jpg', 7, 2007),
('02_04_2021_2728_1', '/our_vehicule/02_04_2021_2728_1.jpg', 7, 2728),
('02_04_2021_2908_1', '/our_vehicule/02_04_2021_2908_1.jpg', 4, 2908),
('02_04_2021_3032_1', '/our_vehicule/02_04_2021_3032_1.jpg', 7, 3032),
('02_04_2021_3252_1', '/our_vehicule/02_04_2021_3252_1.jpg', 7, 3252),
('02_04_2021_4022_1', '/our_vehicule/02_04_2021_4022_1.jpg', 9, 4022),
('02_04_2021_4033_1', '/our_vehicule/02_04_2021_4033_1.jpg', 5, 4033),
('02_04_2021_4127_1', '/our_vehicule/02_04_2021_4127_1.jpg', 3, 4127),
('02_04_2021_4464_1', '/our_vehicule/02_04_2021_4464_1.jpg', 5, 4464),
('02_04_2021_4651_1', '/our_vehicule/02_04_2021_4651_1.jpg', 4, 4651),
('02_04_2021_5185_1', '/our_vehicule/02_04_2021_5185_1.jpg', 11, 5185),
('02_04_2021_5562_1', '/our_vehicule/02_04_2021_5562_1.jpg', 7, 5562),
('02_04_2021_5948_1', '/our_vehicule/02_04_2021_5948_1.jpg', 6, 5948),
('02_04_2021_6048_1', '/our_vehicule/02_04_2021_6048_1.jpg', 7, 6048),
('02_04_2021_6619_1', '/our_vehicule/02_04_2021_6619_1.jpg', 4, 6619);

-- --------------------------------------------------------

--
-- Structure de la table `message`
--

DROP TABLE IF EXISTS `message`;
CREATE TABLE IF NOT EXISTS `message` (
  `id_message` int(10) NOT NULL AUTO_INCREMENT,
  `prenom` varchar(50) NOT NULL,
  `nom` varchar(25) NOT NULL,
  `telephone` int(9) NOT NULL,
  `email` varchar(75) DEFAULT NULL,
  `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `message` text NOT NULL,
  PRIMARY KEY (`id_message`)
) ENGINE=InnoDB AUTO_INCREMENT=164 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `message`
--

INSERT INTO `message` (`id_message`, `prenom`, `nom`, `telephone`, `email`, `date`, `message`) VALUES
(23, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(24, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(25, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(26, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(28, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(29, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(30, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(31, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(33, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(34, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(35, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(36, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(37, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(38, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(39, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(40, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(41, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(42, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(43, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(44, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(45, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(46, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(47, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(48, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(49, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(50, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(51, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(52, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(53, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(54, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(55, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(56, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(57, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(58, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(59, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(60, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(61, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(62, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(63, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(64, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(65, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(66, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(67, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(68, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(69, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(70, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(71, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(72, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(73, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(74, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(75, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(76, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(77, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(78, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(79, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(80, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(81, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(82, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(83, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(84, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(85, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(86, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(87, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(88, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(89, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(90, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(91, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(92, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(93, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(94, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(95, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(96, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(97, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(98, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(99, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(100, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(101, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(102, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(103, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(104, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(105, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(106, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(107, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(108, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(109, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(110, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(111, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(112, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.');
INSERT INTO `message` (`id_message`, `prenom`, `nom`, `telephone`, `email`, `date`, `message`) VALUES
(113, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(114, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(115, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(116, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(117, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(118, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(119, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(120, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(121, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(122, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(123, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(124, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(125, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(126, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(127, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(128, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(129, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(130, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(131, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(132, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(133, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(134, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(135, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(136, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(137, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(138, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(139, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(140, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(141, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(142, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(143, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(144, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(145, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(146, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(147, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(148, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(149, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(150, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(151, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(152, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(153, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(154, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(155, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(156, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(157, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(158, 'Djiby', 'Sarr', 777781562, 'sarrdjiby20@gmail.com', '2021-03-23 12:16:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(159, 'mbene', 'ndiaye', 785639900, 'mbene98ndiaye@gmail.com', '2021-03-10 13:44:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(160, 'Serigne Fallou', 'Mbengue', 768004562, 'mbenguefallou@gmail.com', '2021-03-22 21:29:44', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\n'),
(161, 'Antoine', 'Diop', 786366263, '', '2021-03-28 19:03:14', 'lorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar\r\nlorem ipsum dolar lorem ipsum dolar lorem ipsum dolar'),
(162, 'Binta', 'Kone', 708999292, 'binta-kone2000@gmail.com', '2021-03-29 00:00:00', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit.\r\nAut, iste obcaecati eius repellat optio laudantium eaque\r\nconsequuntur facere eum dolor accusamus,\r\nminima totam tempora accusantium praesentium, nulla eveniet. Eveniet, esse.'),
(163, 'Fallou', 'Niase', 786375432, 'fallou-niasse@gmail.com', '2021-04-25 08:05:33', 'Le ttteg ggsge ghwehwewhjehwjh sdshdjshwjw ewjehjwhejw Le ttteg ggsge ghwehwewhjehwjh sdshdjshwjw ewjehjwhejw Le ttteg ggsge ghwehwewhjehwjh sdshdjshwjw ewjehjwhejw Le ttteg ggsge ghwehwewhjehwjh sdshdjshwjw ewjehjwhejw Le ttteg ggsge ghwehwewhjehwjh sdshdjshwjw ewjehjwhejw Le ttteg ggsge ghwehwewhjehwjh sdshdjshwjw ewjehjwhejw Le ttteg ggsge ghwehwewhjehwjh sdshdjshwjw ewjehjwhejw');

-- --------------------------------------------------------

--
-- Structure de la table `voiture`
--

DROP TABLE IF EXISTS `voiture`;
CREATE TABLE IF NOT EXISTS `voiture` (
  `numero_voiture` int(5) NOT NULL AUTO_INCREMENT,
  `modele` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `marque` varchar(50) CHARACTER SET utf8 NOT NULL,
  `annee` int(4) UNSIGNED DEFAULT NULL,
  `carburant` varchar(15) CHARACTER SET utf8 NOT NULL,
  `kilometrage` varchar(10) DEFAULT NULL,
  `boite_vitesse` varchar(25) CHARACTER SET utf8 DEFAULT NULL,
  `couleur` varchar(50) CHARACTER SET utf8 NOT NULL,
  `prix` int(10) DEFAULT NULL,
  `description` text CHARACTER SET utf8 NOT NULL,
  `etat_voiture` varchar(8) CHARACTER SET utf8 NOT NULL,
  `date_publication` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`numero_voiture`)
) ENGINE=InnoDB AUTO_INCREMENT=6620 DEFAULT CHARSET=utf32;

--
-- Déchargement des données de la table `voiture`
--

INSERT INTO `voiture` (`numero_voiture`, `modele`, `marque`, `annee`, `carburant`, `kilometrage`, `boite_vitesse`, `couleur`, `prix`, `description`, `etat_voiture`, `date_publication`) VALUES
(224, 'Modular Blue Model', 'BMW', 2019, 'Diesel', '225 000', 'Sequenstielle', 'Bleue', 2000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 16:04:46'),
(1016, 'Kia Stinger', 'Kia', 2020, 'Diesel', '150 000', 'Automatic', 'Rouge', 2000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 15:53:29'),
(1257, 'RED CHAMPION 2020', 'BMW', 2019, 'Diesel', '250 000', 'Automatic', 'Rouge', 5000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Neuf', '2021-04-02 16:12:23'),
(2007, 'Kia WEMBLEG 3', 'Kia', 2020, 'Hybride', '175 000', 'Automatic', 'Blanc', 7000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 16:02:52'),
(2728, 'Kia Level 18', 'Kia', 2019, 'Hybride', '325 000', 'Automatic', 'Rouge', 4000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Neuf', '2021-04-02 16:22:58'),
(2908, 'Mercedes Level Vitesse', 'Mercedes', 2019, 'Essence', '225 000', 'Automatic', 'White', 4000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Neuf', '2021-04-02 16:21:25'),
(3032, 'Fiat Chinois', 'Fiat', 2018, 'Essence', '200 000', 'Manuel', 'Jaune', 5000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 16:09:15'),
(3252, 'Grille Allemande New Generation', 'BMW', 2021, 'Diesel', '300 000', 'Automatic', 'Grille Transparent', 2500000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Neuf', '2021-04-02 16:14:00'),
(4022, 'BMW', 'Peugeot', 2012, 'Diesel', '160 000', 'Automatic', 'Bleu', 3500000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 16:15:16'),
(4033, '208 GT', 'Alpine', 2021, 'Hybride', '100 000', 'Manuel', 'Orangered', 3000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 15:35:11'),
(4127, 'Sportage GT Mac', 'Land Rover', 2017, 'Diesel', '200 000', 'Automatic', 'Bleu', 5000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 15:48:48'),
(4464, 'BMW M2', 'BMW', 2019, 'Diesel', '200 000', 'Automatic', 'Bleu', 3000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. \r\nModi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti,\r\nSapiente officiis soluta impedit dolore nobis autem veritatis asperiores.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. \r\nModi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti,\r\nsapiente officiis soluta impedit dolore nobis autem veritatis asperiores.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. \r\nModi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti,\r\nsapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 15:28:33'),
(4651, 'Verna New Model', 'BMW', 2106, 'Essence', '150 000', 'Manuel', 'Bleu Fonce', NULL, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Neuf', '2021-04-02 15:42:41'),
(5185, 'bmw white car', 'BMW', 2018, 'Hybride', '100 000', 'Automatic', 'Blanc', 2000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.\r\n', 'Neuf', '2021-04-02 15:37:58'),
(5562, '208-GT Suedois', 'BMW', 2014, 'Essence', '180 000', 'Automatic', 'Bleu', 8000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 16:19:27'),
(5948, 'American Great Teager Car', 'BMW', 2018, 'Hybride', '160 000', 'Automatic', 'White', 5000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Neuf', '2021-04-02 16:17:17'),
(6048, 'Yellow peugeot', 'Peugeot', 2019, 'Diesel', '150 000', 'Manuel', 'Jaune', 8000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Occasion', '2021-04-02 15:33:29'),
(6619, 'Mercedes White Car', 'Mercedes', 2017, 'Diesel', '200 000', 'Automatic', 'White', 7000000, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, Sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, labore vitae. Modi voluptatum ullam repudiandae quidem consequuntur tenetur facere suscipit corrupti, sapiente officiis soluta impedit dolore nobis autem veritatis asperiores.', 'Neuf', '2021-04-02 16:06:19');

-- --------------------------------------------------------

--
-- Structure de la table `voiture_location`
--

DROP TABLE IF EXISTS `voiture_location`;
CREATE TABLE IF NOT EXISTS `voiture_location` (
  `numero_voiture` int(5) NOT NULL,
  `tarif_par_region` varchar(100) NOT NULL,
  KEY `numero_voiture` (`numero_voiture`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `voiture_location`
--

INSERT INTO `voiture_location` (`numero_voiture`, `tarif_par_region`) VALUES
(4022, '5000-5000-5000-11000-14000-20000-16000-25000-8000-14000-6000-19000-12000-80000'),
(1016, '0-0-0-0-0-0-0-0-0-0-0-0-0-0'),
(4033, '7000-5000-18000-9000-15000-0-20000-18000-0-20000-15000-15000-26000-0');

--
-- Contraintes pour la table `image`
--
ALTER TABLE `image`
  ADD CONSTRAINT `image_ibfk_1` FOREIGN KEY (`numero_voiture`) REFERENCES `voiture` (`numero_voiture`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Contraintes pour la table `voiture_location`
--
ALTER TABLE `voiture_location`
  ADD CONSTRAINT `voiture_location_ibfk_1` FOREIGN KEY (`numero_voiture`) REFERENCES `voiture` (`numero_voiture`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;



-- CREATION DE L'UTILISATEUR
CREATE USER IF NOT EXISTS Djiby_Sarr_1996 IDENTIFIED BY 'djiby_sarr_1996';
GRANT ALL PRIVILEGES ON senegal_auto.* to Djiby_Sarr_1996;
